### ISSUE TITLE
latency definition inconsistency at page docs/2.1.7/general/timings.html

### ISSUE THREAD

**Issue by bekiroguz** [gatling/gatling.github.io#15]
Hi,
at the section describing Latency it is described as the time between the beginning of the request sending and start of the response receiving. But in the detailed explanation, "end of the request sending" is explained. Which is actually correct? I suspect a copy paste mistake here from the previous section "Response Time".

Relevant section: http://gatling.io/docs/2.1.7/general/timings.html#latency 
Latency
The latency is the elapsed time between **the beginning of the request’s sending** and **the start of the response’s receiving**:

**The end of request’s sending** is the instant when the last bytes of the request have been sent over the wire by Gatling.
**The beginning of the response’s receiving** is the instant when at least the response’s HTTP status has been been received by Gatling.

**Comment by slandelle** [comment]
> between the beginning of the request sending 

Yeah, that's the end of the request sending.
Thanks for reporting!

**Comment by slandelle** [comment]
Closing, we centralize issues in main project: https://github.com/gatling/gatling/issues/2827

**Comment by bekiroguz** [comment]
Great, thanks for reacting quickly.
